import sys
from datetime import datetime

def clock_monotonic() -> int: ...
def clock_realtime() -> int: ...
def clock_datetime() -> "datetime.datetime": ...

if sys.platform != "win32":
    def clock_monotonic_raw() -> int: ...
    def clock_monotonic_coarse() -> int: ...
    def clock_realtime_coarse() -> int: ...

def clock_generic(clock_id: int, *, raise_on_error: bool = True) -> int: ...
