from datetime import datetime

def ns_to_datetime(ns_timestamp: int) -> datetime: ...
def us_to_datetime(us_timestamp: int) -> datetime: ...
def ms_to_datetime(ms_timestamp: int) -> datetime: ...
def s_to_datetime(s_timestamp: float) -> datetime: ...
def datetime_to_ns(dt: datetime) -> int: ...
def datetime_to_us(dt: datetime) -> int: ...
def datetime_to_ms(dt: datetime) -> int: ...
def datetime_to_s(dt: datetime) -> float: ...
def change_ts_units(
    timestamp: int, from_unit: str = "ns", to_unit: str = "ns"
) -> int: ...
