import datetime

def parse_rfc2822_bytes_to_timestamp(datestr: bytes) -> float: ...
def parse_rfc2822_bytes_to_timestamp_with_tz(datestr: bytes) -> float: ...
def parse_rfc2822_bytes_to_datetime(datestr: bytes) -> "datetime.datetime": ...
